### ISSUE TITLE
Add notice to enable JavaScript in page shell

### ISSUE THREAD

**Issue by Naleksuh** [leighmacdonald/uncletopia-web#2]
Task https://github.com/leighmacdonald/uncletopia-web/issues/1 has been closed with the refusal to implement a non-JavaScript system into Uncletopia due to the addition of interactive elements.

However, when a user goes to uncletopia.com with JavaScript disabled, all they will see is a brown screen.

Ideally when a user goes to a website which requires JavaScript (like maybe a chat site) there will be a notice asking to enable it like this one:
![image](https://user-images.githubusercontent.com/24828999/131201800-aa131f54-3fec-4165-ba34-dd04c1febcd1.png)

I recommend adding a notice in the page shell such as "Uncletopia.com requires JavaScript for interactive elements, please enable JavaScript to use Uncletopia" or similar in the page shell. This will make it more clear and intuitive than simply a brown screen.

**Comment by Naleksuh** [comment]
Also try not to use the \<noscript\> tag here, it's discouraged as there are many reasons JavaScript may be disabled, but only a subset of them will activate the \<noscript\> tag.

**Comment by leighmacdonald** [comment]
Since you can't seem to take a hint, nor even wait until the ticket it closed to tell me how i did it wrong. And are still taking jabs at using js. I'm just going to block you at this point since you are just wasting our time right now.
