### ISSUE TITLE
Don't show connect button if server is full

### ISSUE THREAD

**Issue by Naleksuh** [leighmacdonald/uncletopia-web#5]
Minor cosmetic enhancement. Obviously players cannot connect if the server is full so no reason to let them try.

**Comment by jonttm** [comment]
I think the connect button should stay so people can use the auto retry function that Steam provides

**Comment by leighmacdonald** [comment]
Disagree as it allows people to launch into the auto-join queue.

**Comment by Naleksuh** [comment]
@leighmacdonald Is there a queue now? Last I tried the Connect button just launches the steam:// URL even if it's full
